/** Temporary preview product data — images live in /public/products and /public/categories. */

export const products = [
  {
    id: '1',
    name: 'Priya Orange Embroidered Chanderi Suit Set',
    price: 5499,
    originalPrice: 5499,
    image: '/products/priya-orange.jpg',
    category: 'suit-sets',
    rating: 4.8,
    stock: 12,
    description: 'Embroidered chanderi suit set in vibrant orange — festive ready.',
  },
  {
    id: '2',
    name: 'Shagun Pink Embroidered Chanderi Suit Set',
    price: 6499,
    originalPrice: 6499,
    image: '/products/shagun-pink.jpg',
    category: 'suit-sets',
    rating: 4.7,
    stock: 10,
    description: 'Pink embroidered chanderi suit set with intricate detailing.',
  },
  {
    id: '3',
    name: 'Anuroop Red Embroidered Chanderi Lehenga Set',
    price: 7999,
    originalPrice: 7999,
    image: '/products/anuroop-red.jpg',
    category: 'lehenga-sets',
    rating: 4.9,
    stock: 8,
    description: 'Red embroidered chanderi lehenga set for celebrations.',
  },
  {
    id: '4',
    name: 'Ambika Purple Embroidered Chanderi Suit Set',
    price: 4199,
    originalPrice: 4199,
    image: '/products/ambika-purple.jpg',
    category: 'suit-sets',
    rating: 4.6,
    stock: 15,
    description: 'Purple embroidered chanderi suit set with elegant finish.',
  },
  {
    id: '5',
    name: 'Mora Blue Embroidered Satin Lehenga Set',
    price: 9699,
    originalPrice: 9699,
    image: '/products/mora-blue.jpg',
    category: 'lehenga-sets',
    rating: 4.8,
    stock: 6,
    description: 'Blue embroidered satin lehenga set for statement evenings.',
  },
  {
    id: '6',
    name: 'Soma Green Embroidered Chanderi Suit Set',
    price: 5999,
    originalPrice: 5999,
    image: '/products/soma-green.jpg',
    category: 'suit-sets',
    rating: 4.7,
    stock: 11,
    description: 'Green embroidered chanderi suit set in a fresh festive tone.',
  },
  {
    id: '7',
    name: 'Ishani Blue Embroidered Chanderi Suit Set',
    price: 4999,
    originalPrice: 4999,
    image: '/products/ishani-blue.jpg',
    category: 'suit-sets',
    rating: 4.5,
    stock: 14,
    description: 'Blue embroidered chanderi suit set for daytime festivities.',
  },
  {
    id: '8',
    name: 'Rajya Grey Embroidered Chanderi Suit Set',
    price: 5999,
    originalPrice: 5999,
    image: '/products/rajya-grey.jpg',
    category: 'suit-sets',
    rating: 4.6,
    stock: 9,
    description: 'Grey embroidered chanderi suit set with understated elegance.',
  },
  {
    id: '9',
    name: 'Vibha Magenta Solid Chanderi Suit Set',
    price: 6894,
    originalPrice: 15320,
    image: '/products/vibha-magenta.jpg',
    category: 'suit-sets',
    rating: 4.8,
    stock: 7,
    description: 'Magenta solid chanderi suit set — Buy 1 Get 1 Free sale.',
  },
  {
    id: '10',
    name: 'Padma Beige Solid Chanderi Suit Set',
    price: 6943,
    originalPrice: 15429,
    image: '/products/padma-beige.jpg',
    category: 'suit-sets',
    rating: 4.7,
    stock: 8,
    description: 'Beige solid chanderi suit set on festive sale.',
  },
  {
    id: '11',
    name: 'Mehka Red Solid Satin Lehenga Set',
    price: 11820,
    originalPrice: 29550,
    image: '/products/mehka-red.jpg',
    category: 'lehenga-sets',
    rating: 4.9,
    stock: 5,
    description: 'Red solid satin lehenga set — ceremony favourite.',
  },
  {
    id: '12',
    name: 'Sparkling Purple Gotapatti Suit Set',
    price: 4999,
    originalPrice: 16663,
    image: '/products/sparkling-purple.png',
    category: 'suit-sets',
    rating: 4.8,
    stock: 16,
    description: 'Gotapatti purple suit set with festive sparkle.',
  },
  {
    id: '13',
    name: 'Neria Gotapatti Tier Suit Set',
    price: 4999,
    originalPrice: 9089,
    image: '/products/neria-gotapatti.png',
    category: 'suit-sets',
    rating: 4.6,
    stock: 13,
    description: 'Tiered gotapatti suit set with layered silhouette.',
  },
  {
    id: '14',
    name: 'Sabine Pink Printed Cotton Stripes Kurta Set',
    price: 3407,
    originalPrice: 7571,
    image: '/products/sabine-pink.jpg',
    category: 'kurta-sets',
    rating: 4.5,
    stock: 20,
    description: 'Pink printed cotton stripes kurta set for everyday ethnic wear.',
  },
  {
    id: '15',
    name: 'Vista White Embroidered Doria Suit Set',
    price: 4999,
    originalPrice: 9998,
    image: '/products/vista-white.jpg',
    category: 'suit-sets',
    rating: 4.7,
    stock: 12,
    description: 'White embroidered doria suit set — light and festive.',
  },
  {
    id: '16',
    name: 'Sakshi Yellow Embroidered Chanderi Suit Set',
    price: 4542,
    originalPrice: 12977,
    image: '/products/sakshi-yellow.jpg',
    category: 'suit-sets',
    rating: 4.6,
    stock: 10,
    description: 'Yellow embroidered chanderi suit set on Tyohar sale.',
  },
  // Kurta Sets
  {
    id: '17',
    name: 'Aarohi Cotton Printed Kurta Set',
    price: 2899,
    originalPrice: 4999,
    image: '/products/ishani-blue.jpg',
    category: 'kurta-sets',
    rating: 4.4,
    stock: 18,
    description: 'Soft cotton printed kurta set for everyday ethnic wear.',
  },
  {
    id: '18',
    name: 'Naina Linen Straight Kurta Set',
    price: 3199,
    originalPrice: 5699,
    image: '/products/soma-green.jpg',
    category: 'kurta-sets',
    rating: 4.6,
    stock: 14,
    description: 'Breathable linen kurta set with straight silhouette.',
  },
  {
    id: '19',
    name: 'Tara Embroidered Kurta Palazzo Set',
    price: 3799,
    originalPrice: 6999,
    image: '/products/vista-white.jpg',
    category: 'kurta-sets',
    rating: 4.7,
    stock: 11,
    description: 'Embroidered kurta with matching palazzo for festive days.',
  },
  // Lehenga Sets (extra)
  {
    id: '20',
    name: 'Kiara Gold Embroidered Lehenga Set',
    price: 12999,
    originalPrice: 24999,
    image: '/products/shagun-pink.jpg',
    category: 'lehenga-sets',
    rating: 4.8,
    stock: 4,
    description: 'Gold-toned embroidered lehenga for wedding evenings.',
  },
  {
    id: '21',
    name: 'Rhea Pastel Organza Lehenga Set',
    price: 10999,
    originalPrice: 21999,
    image: '/products/padma-beige.jpg',
    category: 'lehenga-sets',
    rating: 4.7,
    stock: 6,
    description: 'Pastel organza lehenga with delicate embroidery.',
  },
  // Sharara Sets
  {
    id: '22',
    name: 'Zara Flared Sharara Suit Set',
    price: 5499,
    originalPrice: 9999,
    image: '/products/priya-orange.jpg',
    category: 'sharara-sets',
    rating: 4.6,
    stock: 9,
    description: 'Flared sharara set with festive embroidery.',
  },
  {
    id: '23',
    name: 'Meher Gharara Style Sharara Set',
    price: 6299,
    originalPrice: 11999,
    image: '/products/ambika-purple.jpg',
    category: 'sharara-sets',
    rating: 4.7,
    stock: 8,
    description: 'Gharara-inspired sharara set with rich detailing.',
  },
  {
    id: '24',
    name: 'Inaya Embroidered Sharara Set',
    price: 4999,
    originalPrice: 8999,
    image: '/products/vibha-magenta.jpg',
    category: 'sharara-sets',
    rating: 4.5,
    stock: 12,
    description: 'Embroidered sharara set for festive gatherings.',
  },
  {
    id: '25',
    name: 'Saanvi Sequinned Sharara Set',
    price: 7199,
    originalPrice: 13999,
    image: '/products/sparkling-purple.png',
    category: 'sharara-sets',
    rating: 4.8,
    stock: 7,
    description: 'Sequinned sharara set with party-ready shimmer.',
  },
  // Sarees
  {
    id: '26',
    name: 'Kavya Soft Silk Saree',
    price: 4599,
    originalPrice: 8999,
    image: '/categories/sarees.webp',
    category: 'sarees',
    rating: 4.7,
    stock: 15,
    description: 'Soft silk saree with classic drape and festive sheen.',
  },
  {
    id: '27',
    name: 'Anvi Printed Georgette Saree',
    price: 2999,
    originalPrice: 5499,
    image: '/products/neria-gotapatti.png',
    category: 'sarees',
    rating: 4.4,
    stock: 20,
    description: 'Lightweight printed georgette saree for easy wear.',
  },
  {
    id: '28',
    name: 'Diya Banarasi Weave Saree',
    price: 7999,
    originalPrice: 15999,
    image: '/products/sakshi-yellow.jpg',
    category: 'sarees',
    rating: 4.9,
    stock: 6,
    description: 'Banarasi-inspired weave saree for celebrations.',
  },
  {
    id: '29',
    name: 'Ira Tissue Organza Saree',
    price: 5499,
    originalPrice: 10999,
    image: '/products/rajya-grey.jpg',
    category: 'sarees',
    rating: 4.6,
    stock: 10,
    description: 'Tissue organza saree with a modern festive finish.',
  },
  // Coord Sets
  {
    id: '30',
    name: 'Lila Matching Coord Set',
    price: 3999,
    originalPrice: 7499,
    image: '/categories/coord-sets.webp',
    category: 'coord-sets',
    rating: 4.5,
    stock: 13,
    description: 'Matching ethnic coord set for effortless styling.',
  },
  {
    id: '31',
    name: 'Nyra Crop Top Coord Set',
    price: 4299,
    originalPrice: 7999,
    image: '/products/sabine-pink.jpg',
    category: 'coord-sets',
    rating: 4.6,
    stock: 11,
    description: 'Crop top coord set with contemporary ethnic cuts.',
  },
  {
    id: '32',
    name: 'Veda Printed Coord Set',
    price: 3599,
    originalPrice: 6499,
    image: '/products/ishani-blue.jpg',
    category: 'coord-sets',
    rating: 4.4,
    stock: 16,
    description: 'Printed coord set for day-to-night ethnic looks.',
  },
  {
    id: '33',
    name: 'Aisha Embellished Coord Set',
    price: 4999,
    originalPrice: 9499,
    image: '/products/sparkling-purple.png',
    category: 'coord-sets',
    rating: 4.7,
    stock: 9,
    description: 'Embellished coord set with festive detailing.',
  },
  // Jewellery
  {
    id: '34',
    name: 'Pearl Drop Earrings',
    price: 1299,
    originalPrice: 2499,
    image: '/categories/jewellery.webp',
    category: 'jewellery',
    rating: 4.6,
    stock: 25,
    description: 'Classic pearl drop earrings for everyday elegance.',
  },
  {
    id: '35',
    name: 'Kundan Statement Necklace Set',
    price: 3499,
    originalPrice: 6999,
    image: '/products/mehka-red.jpg',
    category: 'jewellery',
    rating: 4.8,
    stock: 12,
    description: 'Kundan necklace set for bridal and festive looks.',
  },
  {
    id: '36',
    name: 'Gold-Plated Jhumka Earrings',
    price: 999,
    originalPrice: 1999,
    image: '/products/anuroop-red.jpg',
    category: 'jewellery',
    rating: 4.5,
    stock: 30,
    description: 'Gold-plated jhumkas with traditional craftsmanship.',
  },
  {
    id: '37',
    name: 'Minimal Stacking Bangle Set',
    price: 1599,
    originalPrice: 2999,
    image: '/products/mora-blue.jpg',
    category: 'jewellery',
    rating: 4.4,
    stock: 22,
    description: 'Minimal stacking bangles for layered styling.',
  },
  // Footwear
  {
    id: '38',
    name: 'Classic Embroidered Juttis',
    price: 1899,
    originalPrice: 3499,
    image: '/categories/footwear.png',
    category: 'footwear',
    rating: 4.6,
    stock: 18,
    description: 'Hand-embroidered juttis for ethnic ensembles.',
  },
  {
    id: '39',
    name: 'Kolhapuri Leather Sandals',
    price: 2199,
    originalPrice: 3999,
    image: '/products/padma-beige.jpg',
    category: 'footwear',
    rating: 4.5,
    stock: 14,
    description: 'Traditional kolhapuri sandals in soft leather.',
  },
  {
    id: '40',
    name: 'Block Heel Ethnic Mojaris',
    price: 2699,
    originalPrice: 4999,
    image: '/products/priya-orange.jpg',
    category: 'footwear',
    rating: 4.7,
    stock: 10,
    description: 'Block heel mojaris for festive comfort and height.',
  },
  {
    id: '41',
    name: 'Velvet Embellished Slip-Ons',
    price: 2499,
    originalPrice: 4499,
    image: '/products/ambika-purple.jpg',
    category: 'footwear',
    rating: 4.6,
    stock: 12,
    description: 'Velvet slip-ons with subtle festive embellishment.',
  },
];

export const categories = [
  {
    id: '1',
    name: 'Suit Sets',
    slug: 'suit-sets',
    blurb: 'Embroidered & festive suits',
    image: '/categories/suit-sets.jpg',
    imageFocus: 'top',
  },
  {
    id: '2',
    name: 'Kurta Sets',
    slug: 'kurta-sets',
    blurb: 'Everyday ethnic kurtas',
    image: '/categories/kurta-sets.webp',
    imageFocus: 'top',
  },
  {
    id: '3',
    name: 'Lehenga Sets',
    slug: 'lehenga-sets',
    blurb: 'Ceremony lehengas',
    image: '/categories/lehenga-sets.webp',
    imageFocus: 'top',
  },
  {
    id: '4',
    name: 'Sharara Sets',
    slug: 'sharara-sets',
    blurb: 'Flowy festive sets',
    image: '/categories/sharara-sets.jpg',
    imageFocus: 'top',
  },
  {
    id: '5',
    name: 'Sarees',
    slug: 'sarees',
    blurb: 'Classic & modern sarees',
    image: '/categories/sarees.webp',
    imageFit: 'contain',
    imageBg: '#f3ebe3',
  },
  {
    id: '6',
    name: 'Coord Sets',
    slug: 'coord-sets',
    blurb: 'Matching ethnic coords',
    image: '/categories/coord-sets.webp',
    imageFocus: 'top',
  },
  {
    id: '7',
    name: 'Jewellery',
    slug: 'jewellery',
    blurb: 'Earrings & more',
    image: '/categories/jewellery.webp',
    imageFocus: 'center',
  },
  {
    id: '8',
    name: 'Footwear',
    slug: 'footwear',
    blurb: 'Juttis & kolhapuris',
    image: '/categories/footwear.png',
    imageFit: 'contain',
    imageBg: '#c9a66b',
  },
];

export const orders = [
  { id: 'ORD-1001', date: '2024-07-15', total: 10998, status: 'Delivered', items: 2 },
  { id: 'ORD-1002', date: '2024-07-20', total: 4999, status: 'Shipped', items: 1 },
  { id: 'ORD-1003', date: '2024-07-25', total: 7999, status: 'Pending', items: 1 },
];

export const users = [
  { id: '1', name: 'Rahul Sharma', email: 'rahul@example.com', role: 'user', joined: '2024-01-10' },
  { id: '2', name: 'Priya Patel', email: 'priya@example.com', role: 'user', joined: '2024-02-15' },
  { id: '3', name: 'Admin User', email: 'admin@example.com', role: 'admin', joined: '2024-01-01' },
];

/** Product attributes used for filters / variants in admin */
export const attributes = [
  {
    id: '1',
    name: 'Size',
    slug: 'size',
    type: 'select',
    values: ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'Free Size'],
  },
  {
    id: '2',
    name: 'Color',
    slug: 'color',
    type: 'color',
    values: ['Black', 'White', 'Red', 'Pink', 'Orange', 'Purple', 'Blue', 'Green', 'Beige', 'Gold'],
  },
  {
    id: '3',
    name: 'Fabric',
    slug: 'fabric',
    type: 'select',
    values: ['Chanderi', 'Satin', 'Silk', 'Cotton', 'Georgette', 'Velvet', 'Organza'],
  },
  {
    id: '4',
    name: 'Occasion',
    slug: 'occasion',
    type: 'select',
    values: ['Festive', 'Wedding', 'Casual', 'Party', 'Ceremony'],
  },
  {
    id: '5',
    name: 'Work',
    slug: 'work',
    type: 'select',
    values: ['Embroidered', 'Printed', 'Solid', 'Embellished', 'Handcrafted'],
  },
];
